CREATE DATABASE ZABAVYPOS;
USE ZABAVYPOS;

CREATE TABLE USUARIOS (
  `CedUser` VARCHAR(20) NOT NULL,
  `NomUser` VARCHAR(45) NOT NULL,
  `ApelUser` VARCHAR(45) NOT NULL,
  `CelUser` VARCHAR(20) NOT NULL,
  `MailUser` VARCHAR(45) NOT NULL,
  `UserUser` VARCHAR(45) NOT NULL,
  `PassUser` VARCHAR(45) NOT NULL,
  `Admin` BIT NULL DEFAULT 0,
  PRIMARY KEY (`CedUser`),
  UNIQUE INDEX `CedUser_UNIQUE` (`CedUser` ASC),
  UNIQUE INDEX `UserUser_UNIQUE` (`UserUser` ASC));
  
  INSERT INTO USUARIOS VALUES ('1128439829', 'JUANEZ', '...', '5277549', '3046838352', 'JUANEZCERE@GMAIL.COM', 'JUANEZ', 'JUANEZ2191', 1, 1);
  
CREATE TABLE CLIENTES (
  `CedCliente` VARCHAR(20) NOT NULL,
  `NomCliente` VARCHAR(45) NOT NULL,
  `ApelCliente` VARCHAR(45) NOT NULL,
  `CelCliente` VARCHAR(20) NOT NULL,
  `MailCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CedCliente`),
  UNIQUE INDEX `CedCliente_UNIQUE` (`CedCliente` ASC),
  UNIQUE INDEX `UserCliente_UNIQUE` (`UserCliente` ASC));

CREATE TABLE PRODUCTOS (
  `IdProd` INT UNSIGNED AUTO_INCREMENT,
  `Producto` VARCHAR(45) NOT NULL,
  `NomProd` VARCHAR(45) NOT NULL,
  `ValorProd` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `IVA` BIT NOT NULL DEFAULT 0,
  `IVAValor` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `Inventario` BIT NOT NULL DEFAULT 0,
  `Habilitado` BIT NOT NULL DEFAULT 0,
  `POS` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdProd`),
  UNIQUE INDEX `IdProducto_UNIQUE` (`IdProd` ASC),
  UNIQUE INDEX `Producto_UNIQUE` (`Producto` ASC));

CREATE TABLE HISTORIAL (
  `IdMaquina` INT UNSIGNED NOT NULL,
  `IdProd` INT UNSIGNED NOT NULL,
  `CedUser` VARCHAR(10) NOT NULL DEFAULT '0000000000',
  `Valor` INT NOT NULL DEFAULT 0,
  `Pago` VARCHAR(10),
  `Fecha` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');

CREATE TABLE TABPDV (
  `IdTabPDV` INT UNSIGNED,
  `Texto` VARCHAR(45) NOT NULL,
  `ColorR` INT NOT NULL DEFAULT 0,
  `ColorG` INT NOT NULL DEFAULT 0,
  `ColorB` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdTabPDV`),
  UNIQUE INDEX `IdPDV_UNIQUE` (`IdTabPDV` ASC));
  
CREATE TABLE PDV (
  `IdPDV` INT UNSIGNED AUTO_INCREMENT,
  `Texto` VARCHAR(45) NOT NULL,
  `ColorR` INT NOT NULL DEFAULT 0,
  `ColorG` INT NOT NULL DEFAULT 0,
  `ColorB` INT NOT NULL DEFAULT 0,
  `LetraR` INT NOT NULL DEFAULT 0,
  `LetraG` INT NOT NULL DEFAULT 0,
  `LetraB` INT NOT NULL DEFAULT 0,
  `X` INT NOT NULL DEFAULT 0,
  `Y` INT NOT NULL DEFAULT 0,
  `H` INT NOT NULL DEFAULT 0,
  `W` INT NOT NULL DEFAULT 0,
  `Imagen` LONGBLOB NULL,
  `IdProd` INT NOT NULL DEFAULT 0,
  `Habilitado` BIT NOT NULL DEFAULT 0,
  `IdMaq` INT NOT NULL DEFAULT 0,
  `IdTabPDV` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdPDV`),
  UNIQUE INDEX `IdPDV_UNIQUE` (`IdPDV` ASC));

CREATE TABLE INVENTARIO (
  `IdProd` INT NOT NULL,
  `CantProd` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdProd`),
  UNIQUE INDEX `IdProd_UNIQUE` (`IdProd` ASC));

CREATE TABLE FACTURAS (
  `IdFactura` INT UNSIGNED AUTO_INCREMENT,
  `Factura` VARCHAR(10) NOT NULL DEFAULT 'ZABAVY-',
  `IdFact` INT UNSIGNED NOT NULL,
  `FactIVA` FLOAT UNSIGNED NOT NULL,
  `FactNeto` FLOAT UNSIGNED NOT NULL,
  `FactTotal` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `FactPagado` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `FactDevuelta` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `FactPago` VARCHAR(10) NOT NULL DEFAULT 'EFECTIVO',
  `Fecha` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Voucher` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdFactura`),
  UNIQUE INDEX `IdFactura_UNIQUE` (`IdFactura` ASC));